Repository AASF-IIITM/aasf-website-backend, pull requests merged in 2021-10, with the labels that each got.

#31 Removed unnecessary development log from production
  server/api/services/events.service.js
Labels: hacktoberfest-accepted

#38 Restructure user schema to separate achievements from user model
  server/api/controllers/users/controller.js
  server/api/services/events.service.js
  server/api/services/users.service.js
  server/models/achievement.js
  server/models/user.js
Labels: hard, hacktoberfest-accepted

#40 #35 Added hashing of default password
  server/api/services/users.service.js
  server/models/user.js
Labels: hacktoberfest-accepted, easy

#41 Added Forgot Password Feature
  README.md
  server/api/controllers/users/controller.js
  server/api/controllers/users/router.js
  server/api/services/mailer.service.js
  server/api/services/users.service.js
  server/models/otp.js
  server/utils/emailTemplates/otpTemplate.js
  server/utils/otpGenerator.js
Labels: hard, hacktoberfest-accepted

#44 Added API documentation for forgot and reset password
  server/api/controllers/admin/controllers/users/controller.js
  server/api/services/users.service.js
  server/common/api.yml
Labels: hacktoberfest-accepted, easy

#46 implemented express-rate-limit
  .env.example
  package-lock.json
  package.json
  server/common/server.js
  test/users.test.js
Labels: hacktoberfest-accepted

#50 Modified otp template
  server/api/services/mailer.service.js
  server/utils/emailTemplates/otpTemplate.js
Labels: hacktoberfest-accepted, easy

#52 added event reminder route
  server/api/controllers/admin/controllers/events/controller.js
  server/api/controllers/admin/controllers/events/router.js
  server/api/controllers/events/controller.js
  server/api/services/events.service.js
  server/api/services/mailer.service.js
  server/utils/emailRecipients.js
  server/utils/emailTemplates/eventTemplate.js
Labels: intermediate, hacktoberfest-accepted

#51 Update README.md
  README.md
Labels: hacktoberfest-accepted, easy
